### ISSUE TITLE
Fails to recognise Flux is installed following enable GitOps

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/vscode-gitops-tools#219] opened 2022-03-07 12:14 UTC
### Expected behaviour

After install, sources and workloads view should update to allow to create resources.

### Actual behaviour

Ran install, install completed, no updates. Tried refreshing cluster/sources view. Tried show cluster info to confirm that the deployment was ready.
<img width="1031" alt="Screenshot 2022-03-07 at 12 12 13" src="https://user-images.githubusercontent.com/19860021/157032348-de175f0b-83c2-47c8-95c9-6dde7f713208.png">

### Steps to reproduce

Create minikube cluster
Enable GitOps

### Versions

k8s - minikube 1.24.0
kubectl version: 1.21.5
Flux version: 0.27.3
Git version:
Azure version:
Extension version: 0.19.0
VSCode version: 
Operating System (OS) and its version: MacOS 12.12.1

**Comment by sympatheticmoose** [comment] 2022-03-07 12:17
quitting VS Code and restarting seems to work

**Comment by kingdonb** [comment] 2022-04-30 12:12
Duplicate of (I think)

* #215 

(Closed in 0.19.1)

**Closed by kingdonb** 2022-04-30 12:12 UTC
Labels: bug

**Comment by kingdonb** [comment] 2022-04-30 12:14
I recognize this issue as something I had dealt with myself in 0.19.0 and I believe it's the same issue that I was initially reporting in #239.

What remains is, I think, an edge case where clusters do not get deleted from the list when they've been removed from kubeconfig.
